- Migrate to .environment instead of hardcoding PHP executables / paths
git-svn-id: svn://svn.xp-framework.net/xp/trunk@8006 d2cacbed-c0f6-0310-851a-9dad52fc623a

diff --git a/experiments/people/friebe/jay/xp5 b/experiments/people/friebe/jay/xp5
--- a/experiments/people/friebe/jay/xp5
+++ b/experiments/people/friebe/jay/xp5
@@ -1,17 +1,33 @@
 #!/bin/sh
 
+readEnv() {
+  ARG=$1
+
+  if [ ! -e `dirname $0`/.environment ] ; then
+    echo "*** Environment not found, please run configure first"
+    return 1;
+  fi
+  
+  SETTING=`grep ^$ARG= .environment | cut -d '=' -f 2`
+  
+  if [ "" = "$SETTING" ] ; then
+    echo "*** Setting $ARG not contained in environment!"
+    return 1;
+  fi
+  
+  return 0;
+}
+
+# {{{ main
+readEnv "php4" && PHPFOUR=$SETTING || exit
+readEnv "php5" && PHPFIVE=$SETTING || exit
+
 if [ "$OS" = "Windows_NT" ] ; then
   # Cygwin
-
-  PHPFOUR="/cygdrive/c/Programme/php-4.4.2-Win32/php.exe"
-  PHPFIVE="/cygdrive/c/Programme/php-5.1.4-Win32/php.exe"
   REALPATH="cygpath -w"
   TEMP="."
 else 
   # Unix
-
-  PHPFOUR=`which php`
-  PHPFIVE=`which php5`
   TEMP="/tmp/"
   REALPATH="realpath"
 fi
@@ -29,3 +45,5 @@ $PHPFIVE -d auto_prepend_file=php5-emit/__xp__.php $TEMP/t.php5 $2 $3 $4 $5 $6 $
 
 # Cleanup
 rm $TEMP/errors $TEMP/t.php5
+
+# }}}
